# Autostart processes
exec-once = alacritty -e tmux new -A -s work
exec-once = google-chrome-stable --profile-directory="Default" https://claude.ai https://github.com/totosuki
exec-once = google-chrome-stable --profile-directory="Profile 1" https://lms-tokyo.iput.ac.jp https://nkzacjp-my.sharepoint.com/my?id=%2Fpersonal%2Ftk240070%5Ftks%5Fiput%5Fac%5Fjp%2FDocuments%2FIPUT%2F2026%E5%89%8D%E6%9C%9F&viewid=bb315147%2D50fe%2D41f3%2Dbcee%2D9c9c72b2c122
exec-once = slack
