
# NVIDIA (Turing+ with GSP firmware)
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Cursor
env = HYPRCURSOR_THEME,catppuccin-mocha-light-cursors
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,catppuccin-mocha-light-cursors
env = XCURSOR_SIZE,24

