# Workspasce Settings
windowrule = workspace 1, match:class ^(obsidian|org.gnome.Evince)$
windowrule = workspace 2, match:class ^(Alacritty)$
windowrule = workspace 3, match:class ^(code)$
windowrule = workspace 4, match:class ^(google-chrome)$
windowrule = workspace 5, match:class ^(slack|chrome-discord.com__channels_@me-Default)$

# Evince
windowrule = tag -floating-window, match:class ^(org.gnome.Evince)$

